### ISSUE TITLE
lscs_force_use spams an extreme amount of netmessages.

### ISSUE THREAD

**Issue by NathanX-S** [SpaxscE/lscs_public#47]
We should only be toggling force, not constantly spamming, or using an alternative method.

**Comment by SpaxscE** [comment]
it already is toggle

**Comment by NathanX-S** [comment]
It's not toggling on my server, and force users are flagging up anti-exploit and I have traced the issue back to LSCS. I can try and get some more solid stats.

**Comment by NathanX-S** [comment]
Logging and testing on myself seems fine, but I've logged users absolutely spamming the hell out of it (across multiple clients that seem otherwise innocent.) Possibly an issue of conflicting/outdated files?

**Comment by SpaxscE** [comment]
This may be caused by their keyboard itself spamming the keys or an autoclicker.

Other than that, spam can happen if you are using a old version (more than 1 year old, which is very unlikely) that does not have IsFirstTimePredicted() in ButtonDown/Up hook as seen here: https://github.com/SpaxscE/lscs_public/blob/main/lua/lscs/autorun/cl_forcepowers.lua#L352-L363

I did some testings today, but i couldnt really find anything else that could cause this. There are no possible conflictions with different input methods such as mixing direct input, forcemenu, or mousescroller with forcemenu/direct input and no other possible feedback loops that i could think of. 


One possible source for alot of netmessages from client to server could be the client responding to the servers ForceStop request on Death. This isnt really needed, but i doubt this is whats causing your issue, but i will change it later when i have time

See:
(Server sending stop request on death, it doesnt really need to send all IDs this should be just a single message to client)
https://github.com/SpaxscE/lscs_public/blob/main/lua/lscs/autorun/lscs_forcepowers.lua#L186-L204

(Client receiving stop request, but sending a message back to server when all it really needs to do is set ID_IN_USE = nil)
https://github.com/SpaxscE/lscs_public/blob/main/lua/lscs/autorun/cl_forcepowers.lua#L149-L162

(Server receiving player stopforceuse request which is completely unneeded because the server already took care of it in PlayerDeath)
https://github.com/SpaxscE/lscs_public/blob/main/lua/lscs/autorun/lscs_forcepowers.lua#L133
